### ISSUE TITLE
[Bug] A Node.js API is used (fs.readFileSync) which is not supported in the Edge Runtime 

### ISSUE THREAD

**Issue by jaukia** [pinecone-io/pinecone-ts-client#108]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Getting error like this:

[0] - error ./node_modules/@pinecone-database/pinecone/dist/utils/user-agent.js:27:22
[0] Module not found: Can't resolve 'fs'
[0] 
[0] https://nextjs.org/docs/messages/module-not-found
[0] 
[0] Import trace for requested module:
[0] ./node_modules/@pinecone-database/pinecone/dist/utils/index.js
[0] ./node_modules/@pinecone-database/pinecone/dist/pinecone.js
[0] ./node_modules/@pinecone-database/pinecone/dist/index.js

Looks like user-agent assumes fs exists.

### Expected Behavior

Pinecone would work even on edge

### Steps To Reproduce

Call Pinecone from node:

const pinecone = new Pinecone({
      apiKey: process.env.PINECONE_API_KEY,
      environment: process.env.PINECONE_ENVIRONMENT
    });
const pineconeIndex = pinecone.index(process.env.PINECONE_INDEX).namespace('ns1');

...

const value = await index.query({
    topK: topK,
    vector: embeddingResponse.data[0].embedding,
    filter: filter,
  });

### Environment

```markdown
- **OS**: Mac
- **Language version**: TypeScript
- **Pinecone client version**: 1.0.0
```

**Comment by jaukia** [comment]
Trying to downgrade to 0.1.6. gives me this error:

[0]  [PineconeError: PineconeClient: Error calling query: PineconeError: PineconeClient: Error calling queryRaw: FetchError: The request failed and the interceptors did not return an alternative response] {
[0]   name: 'PineconeError'

Has the API changed or am I doing something wrong?

**Comment by RickRyan26** [comment]
Same problem. The only reason im using Pinecone in particular is for the Edge.

**Comment by jhamon** [comment]
Sorry for the trouble, I'll try to get a fix for this up soon.

**Comment by jhamon** [comment]
I have one other feature and some more integration testing I want to finish before cutting a 1.1.0 release this week, but if you want to kick the tires on a dev build with changes from #110 in it then you can temporarily install `1.0.0-dev.20230913190611`. I added another CI build using their official test util [`@edge-runtime/jest-environment`](https://edge-runtime.vercel.app/packages/jest-environment) to verify the changes, but haven't yet tried them in a real life Edge Runtime situation since.

**Comment by RickRyan26** [comment]
Thanks! Still not working those. Here's where I'm at. Seems like the fs issue is solved.

```
<html>
<body>
<!--StartFragment-->

> Using @sveltejs/adapter-vercel
--
23:17:26.331 | ✘ [ERROR] Could not resolve "os"
23:17:26.332 |  
23:17:26.332 | node_modules/.pnpm/@pinecone-database+pinecone@**1.0.0-dev.20230913190611**/node_modules/@pinecone-database/pinecone/dist/utils/os.js:27:30:
23:17:26.332 | 27 │ var os = __importStar(require("os"));
23:17:26.332 | │                               ~~~~
23:17:26.333 | ╵                               "./os"
23:17:26.333 |  
23:17:26.333 | The package "os" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
23:17:26.333 |  
23:17:26.518 | error during build:
23:17:26.518 | Error: Build failed with 1 error:
23:17:26.518 | node_modules/.pnpm/@pinecone-database+pinecone@1.0.0-dev.20230913190611/node_modules/@pinecone-database/pinecone/dist/utils/os.js:27:30: ERROR: Could not resolve "os"
23:17:26.518 | at failureErrorWithLog (/vercel/path0/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649:15)
23:17:26.518 | at /vercel/path0/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1058:25
23:17:26.518 | at /vercel/path0/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1003:52
23:17:26.519 | at buildResponseToResult (/vercel/path0/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1056:7)
23:17:26.519 | at /vercel/path0/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1085:16
23:17:26.519 | at responseCallbacks.<computed> (/vercel/path0/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:703:9)
23:17:26.519 | at handleIncomingPacket (/vercel/path0/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:762:9)
23:17:26.519 | at Socket.readFromStdout (/vercel/path0/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:679:7)
23:17:26.519 | at Socket.emit (node:events:514:28)
23:17:26.519 | at addChunk (node:internal/streams/readable:324:12)
23:17:26.602 | ELIFECYCLE  Command failed with exit code 1.
23:17:26.623 | Error: Command "pnpm run build" exited with 1

<!--EndFragment-->
</body>
</html>
```

**Comment by jhamon** [comment]
Thanks for giving it a go. I'm kind of surprised since the `@edge-runtime/jest-environment` didn't flag it, but I guess it shows the need for a true integration test in a real environment to have total confidence. I'll add that to my todo list 😂 

I'll just rip out the `os` bits completely for now so I can ship a fix for this along with some fixes on typescript compilation issues.

**Comment by zackproser** [comment]
+1 - this affects https://github.com/pinecone-io/pinecone-vercel-starter

**Comment by jhamon** [comment]
The `1.0.1` release is out. Release notes [here](https://github.com/pinecone-io/pinecone-ts-client/releases/tag/v1.0.1). I removed the reference to `os` so 🤞 

Try it out and let me know if you're still having problems.

**Comment by RickRyan26** [comment]
It works! You're awesome. Thanks for the special thanks :)
