### ISSUE TITLE
README - waiting until this index is ready confusing code snippet

### ISSUE THREAD

**Issue by zackproser** [pinecone-io/pinecone-ts-client#111]
Currently in [this section of the README](https://github.com/pinecone-io/pinecone-ts-client#waiting-until-the-index-is-ready) we have: 

```javascript
const client = new Pinecone();
// Shouldn't this next line be await client? Or really the above line be const pinecone = new Pinecone()?
await pinecone.createIndex({
  name: 'sample-index',
  dimension: 1536,
  waitUntilReady: true,
});
```

But this seems to run contrary to suggested patterns within the code itself. Is this a mistake? Happy to submit a PR if so, just wanted to confirm first.

**Comment by jhamon** [comment]
Yeah, this is a typo. Thanks for pointing it out. It should be `const pinecone = new Pinecone();`

If you want to make the fix I'll merge right away.
