### ISSUE TITLE
describeIndexStats() promise failing

### ISSUE THREAD

**Issue by deemonic** [pinecone-io/pinecone-ts-client#118]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm trying to call the describeIndexStats() function in order to check the record count for a specific index but it does not appear to be working, a keep getting a **index.ts:11 Uncaught (in promise)**  error in the console. 

I have gone over the pinecone documentation a few times to ensure that my code is correct and this is what I have

```
import { Pinecone } from '@pinecone-database/pinecone'

const pinecone = new Pinecone({
  apiKey: "YOUR_API_KEY",
  environment: "YOUR_ENVIRONMENT"
})

const myFunction = async () => {

const index = pinecone.index("my-index")

const stats= await index.describeIndexStats()

console.log(stats)

}
```

### Expected Behavior

To return a 200 response

### Steps To Reproduce

1. install npm
2. install pinecone
3. run this code ensure you change the API_KEY and ENVIROMENT variables and specify your own pinecone index

```
import { Pinecone } from '@pinecone-database/pinecone'

const pinecone = new Pinecone({
  apiKey: "YOUR_API_KEY",
  environment: "YOUR_ENVIRONMENT"
})

const index = pinecone.index("my-index")

const stats= await index.describeIndexStats()

```

### Environment

```markdown
- **OS**: Windows 11 
- **Pinecone client version**: 0.1.6
- **Node JS**: 18.16.0
```

**Comment by jhamon** [comment]
Thanks for the report. I think this is related to an issue with `cross-fetch` polyfill not getting enabled properly in some cases. I have already fixed that problem in main, and expect to cut a `1.0.1` release with that and a few other bug fixes this evening or tomorrow.

**Comment by deemonic** [comment]
Thanks for the quick response... Brilliant I will keep and eye out for the release.

Many Thanks

**Comment by jhamon** [comment]
The `1.0.1` release is out. Release notes [here](https://github.com/pinecone-io/pinecone-ts-client/releases/tag/v1.0.1). Please try it out and let me know if you're still having problems.

**Comment by deemonic** [comment]
Apologies for the delay...

This release has fixed the issue, I can now called the describeIndexStats() and get a successful response.

Many Thanks
