### ISSUE TITLE
PineconeClient: Project name not set. Call init() first

### ISSUE THREAD

**Issue by ediardo** [pinecone-io/pinecone-ts-client#12]
Hi!

First day using Pinecone. I followed the steps at https://docs.pinecone.io/docs/node-client but I'm getting an error.

Version: 0.0.8

Code:

```ts
 const pinecone = new PineconeClient();
  await pinecone.init({
    environment: "us-east1-gcp",
    apiKey: "SECRET",
  });

  const index = pinecone.Index("websites");

  try {
    const res = await index.upsert({
      upsertRequest: {
        vectors: [
          {
            id: "1",
            values: vector,
          },
        ],
      },
    });
....
```

Error:
```
Error: PineconeClient: Project name not set. Call init() first.
    at PineconeClient.Index (./node_modules/@pinecone-database/pinecone/dist/index.js:172:19)
    at insertToVectorCollection (embeddings.js:50:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createIndex (index.js:77:9)
```

I tried setting the projectName right before the `init()` but didn't make a difference:

```ts
const pinecone = new PineconeClient();
pinecone.projectName = "websites";
await pinecone.init({...
```

What can I do to fix problem?

Thank you.

**Comment by NCKLS** [comment]
I'm also receiving this error. It looks like I'm getting a
```PineconeClient: Error getting project name: ReferenceError: fetch is not defined```
error.

Quickly looking through the source code it seems it's trying to use the jsdom version of fetch and isn't using node-fetch or axios?

**Comment by JoshuaPerk** [comment]
+1

It looks like the `PineconeClient.prototype.Index` function checks for an `apiKey`, `projectName`, and `environment` to assemble the URL for `indexConfigurationParameters`.

But when init'ing, that `projectName` key is stripped away:
```
await pinecone.init({
    environment: process.env.PINECONE_ENVIRONMENT,
    apiKey: process.env.PINECONE_API_KEY,
    projectName: 'Project Name Here'
})
```
👆🏼 This will not working. I'm going to use http requests directly until this is fixed.

P.S. The documentation says to call `pinecone.index(process.env.PINECONE_INDEX)` but it's worth nothing the `i` in `index` needs to be capitalized.

**Comment by rschwabco** [comment]
@ediardo , @NCKLS , @JoshuaPerk - what Node version are you using? This is most likely an issue with using a version of Node that doesn't support `fetch` natively.

**Comment by rschwabco** [comment]
I've added an `engines` version specification:
```
  "engines": {
    "node": ">=18.0.0"
  },
```

**Comment by drob** [comment]
I'm running v16.19 in prod and unfortunately can't upgrade, so this would force me to switch to a different library.

Would strongly prefer an approach like the one in rileytomasek/pinecone-client, i.e. allow older versions of node via a fetch polyfill. If you wanted to make it extra user friendly, you could detect the absence of native `fetch` and warn about it.

**Comment by rschwabco** [comment]
@drob as you suggested [this PR](https://github.com/pinecone-io/pinecone-ts-client/pull/13) add the `cross-fetch` polyfill.

**Comment by junhyeokkwak** [comment]
Seems like this issue was resolved at `0.0.10` but was then reintroduced in `0.0.11`?

**Comment by Thushan96** [comment]
i use Node.js v18.15.0 , i also get the same error

**Comment by markwwd** [comment]
I use Node 16.17.1 and get the same error..

"Error: PineconeClient: Project name not set. Call init() first."

anyone?

**Comment by rschwabco** [comment]
@markwwd @junhyeokkwak @Thushan96 - Can you please provides steps for a repro?

**Comment by Flowko** [comment]
im afraid this has nothing to do with node version nor the fetch issue, but correct me if im wrong, i forked this repo updated it so i can check the fetch situation, fetching the project name endpoint is working as expected, but the issue seems to presist even tho i changed back to using node-fetch.

im using this library in combo with nuxt3 and langchainjs, and locally it works great, when building i can see that the init is setting the correct fields. but that doesnt seem to be carried out when i try to preview it,it always throws this error `Project name not set. Call init() first`, went back to my forked repo and added some logs, it seems that when setting the `projectName` inside of `init` it works fine, but when i tried to retreive that value its always null. back to what i said above, the init gets called on the build but somehow the class fields are not persisted when running the build preview.

this is as far as what i was able to find, not sure about others, but sadly i cant create repoduction, since im trying to use it inside of a private repo.

**Comment by ZYJLiu** [comment]
Was just having same issue working through the demo and updating to "@pinecone-database/pinecone": "^0.0.10" in package.json seems to fix it.

```
  "dependencies": {
    "@pinecone-database/pinecone": "^0.0.10"
    ...
  },
```

**Comment by markwwd** [comment]
@rschwabco I solved it by using the latest NodeJS version. Though, it's giving a warning that it's an experimental feature and it might get replaced in the future (the fetch method).

**Comment by joschan21** [comment]
Having the same issue. 
"PineconeClient: Error getting project name: ReferenceError: fetch is not defined"

**Comment by stephenkalnoske-sans** [comment]
Also had this issue. Reverting back to version 0.0.10 fixed it for me.

**Comment by jlancaster7** [comment]
Also having this issue on node v16.19.1. Reverting to 0.0.10 worked for me.

**Comment by rschwabco** [comment]
There was a build issue that resulted in the `cross-fetch` polyfill to be dropped from the build. Apologies. The error was corrected in `0.0.12`. The issue stems from a mistake where tests were pointing to the `src` directory instead of the `dist` directory, and so the issue wasn't caught during testing.

**Comment by katalystkat** [comment]
hiya new to pinecone, am also having the same errors. 

To recreate-- I cloned the repo from : https://github.com/mayooear/gpt4-pdf-chatbot-langchain && inputted my own API keys for OpenAI and PineCone. I've confirmed that my API keys work for both because when I removed them individually, I receive the expected corresponding errors of needing respective keys. 

@rschwabco I am running Node 19.7, and I've tried updating my pinecone to 0.0.10 and 0.0.12 and both are returning below: 

PineconeClient: Error getting project name: TypeError: fetch failed
[Error: PineconeClient: Project name not set. Call init() first.]

**Comment by felipeotarola** [comment]
> I am facing the same issue When I try to run the app, I get following error
> 
> PineconeClient: Error getting project name: TypeError: fetch failed
> 
> error - [Error: PineconeClient: Project name not set. Call init() first.] { page: ‘/api/chat’ }
> 
> My node version is node -v v18.15.0 Pinecone version is “@pinecone-database/pinecone”: “^0.0.10”,
> 
> It seems it is due to issue of fetch() which is an experimental feature. How to disable fetch() and use node-fetch()

Had same problem. using node Node.js below 17 , 
Got further when adding 
pinecone.projectName = "Pinecone Demo" in the initPinecone() function in pinecone-client.ts
But this mess the url that is created later in the library. 
the the url looks like this
 https://testy-PineconeDemo.svc.testy-54978f2.svc.us-east1-gcp.pinecone.io 
 
 with latest node 19 something, I do not get the init problem. But if I don't specify the pinecone.projectName the url in the library is looking like this
 
https://testy-undefined.svc.testy-54978f2.svc.us-east1-gcp.pinecone.io  

Been hustling for 2 days with this.

**Comment by PMLS3** [comment]
Also getting the error: PineconeClient: Project name not set. Call init() first. at PineconeClient.Index (/usr/src/app/.output/server/node_modules/@pinecone-database/pinecone/dist/index.js

Upgraded my Docker version to Node.js 18.5 - error remains. "@pinecone-database/pinecone": "^0.0.11",

**Comment by rohitdhamija** [comment]
I did  "@pinecone-database/pinecone": "^0.0.12", in package.json and did install again. it seems to be working fine

**Comment by felipeotarola** [comment]
what langchain version do you have? I get conflict with langchain 0.0.41

**Comment by PMLS3** [comment]
> I did "@pinecone-database/pinecone": "^0.0.12", in package.json and did install again. it seems to be working fine

Upgraded but sitting with same issue

**Comment by rohitdhamija** [comment]
> > I did "@pinecone-database/pinecone": "^0.0.12", in package.json and did install again. it seems to be working fine
> 
> Upgraded but sitting with same issue

What is your node version?? Mine is 18.5

**Comment by PMLS3** [comment]
> > > I did "@pinecone-database/pinecone": "^0.0.12", in package.json and did install again. it seems to be working fine
> > 
> > 
> > Upgraded but sitting with same issue
> 
> What is your node version?? Mine is 18.5

Correct yes
Nuxi 3.3.2
ℹ Node.js version: 18.15.0
"@pinecone-database/pinecone": "^0.0.12"
"langchain": "^0.0.33"

**Comment by rohitdhamija** [comment]
Are you behind some proxy?

**Comment by rohitdhamija** [comment]
I think you should pull the code again, there has been changes last night in the code. 
B/w  "langchain": "0.0.41", is that i am using

**Comment by felipeotarola** [comment]
I updated to 0.0.12 but got a new error. 
now it complains about 

error [ErrorWithoutStackTrace: PineconeClient: Error getting project name: TypeError: fetch failed]

even when I set the variable in the client.

**Comment by PMLS3** [comment]
> I think you should pull the code again, there has been changes last night in the code. B/w "langchain": "0.0.41", is that i am using

Still getting the error: 

Error: PineconeClient: Project name not set. Call init() first. at PineconeClient.Index (/usr/src/app/.output/server/node_modules/@pinecone-database/pinecone/dist/index.js:251:19) at upsertVectors (file:///usr/src/app/.output/server/chunks/index3.mjs:58:28) at file:///usr/src/app/.output/server/chunks/create.post2.mjs:11:24 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Object.handler (file:///usr/src/app/.output/server/node_modules/h3/dist/index.mjs:1247:19) at async Server.toNodeHandle (file:///usr/src/app/.output/server/node_modules/h3/dist/index.mjs:1322:7)


Deleted package-lock.json and node-modules

@pinecone-database/pinecone": "^0.0.12"
"langchain": "^0.0.41"

Deployed on Google cloud

**Comment by felipeotarola** [comment]
@PMLS3 
Yes, Im also deploying to google clouds, the problem here is that when you deploy a new installation of node_modules happens. 

Want to co op in discord? 
my username is WhiteRhino#7935

**Comment by PMLS3** [comment]
Got it working on myside, have to call init everytime I call a function...

**Comment by rschwabco** [comment]
@PMLS3 that definitely shouldn't be the case. You should only have to call `init` once. If you share a repro I could hopefully help resolve this.

**Comment by katalystkat** [comment]
@rschwabco  

I currently have the pinecone environment set to 'us-central1-gcp' because that is what is shown on my pinecone dashboard. 

I've rotated and tried a new API key as well but am still receiving the same error on my local machine. I tested my API key & environment via Pinecone API Reference (https://docs.pinecone.io/reference/list_collections) and I was able to get a 200 response there.

**Comment by bschleter** [comment]
Hate to add an extra comment but I too am getting this error. I have checked api key, index name, even added project name in there with the https://github.com/mayooear/gpt4-pdf-chatbot-langchain repo. 

I am running node 18.16 I believe. One odd thing is that after loading my vectors which I got called as successful, I was still unable to view them with fetch on pinecone dashboard. I uploaded 1000 or so vectors. 

Shame because I finally got it…locally ok until I make a call.

**Comment by mariobm** [comment]
Why is this one closed? I'm getting the same error and I'm using this langchain example here: https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/pinecone#index-docs

**Comment by rschwabco** [comment]
@mariobm Langchain seems to be using an outed version of the client (0.0.10 instead of 0.0.13).

**Comment by mberman84** [comment]
I'm still getting this error as well. I cloned the repo everyone is talking about, then I upgraded the pinecone version to 0.0.1.2, and am using node ~18. I'm getting this error:

error [ErrorWithoutStackTrace: PineconeClient: Error getting project name: SyntaxError: Unexpected token A in JSON at position 0]
/Users/matthewberman/Desktop/gpt4-pdf-chatbot-langchain/utils/pinecone-client.ts:19
    throw new Error('Failed to initialize Pinecone Client');

**Comment by bschleter** [comment]
> I'm still getting this error as well. I cloned the repo everyone is talking about, then I upgraded the pinecone version to 0.0.1.2, and am using node ~18. I'm getting this error:
> 
> 
> 
> error [ErrorWithoutStackTrace: PineconeClient: Error getting project name: SyntaxError: Unexpected token A in JSON at position 0]
> 
> /Users/matthewberman/Desktop/gpt4-pdf-chatbot-langchain/utils/pinecone-client.ts:19
> 
>     throw new Error('Failed to initialize Pinecone Client');


Did you try adding the project # in the pinecone.ts? Project number a weird hash like '13h5ja' before the -gcp-1-east or whatever. Not near a computer so don't have a snapshot of my example. The one used has it after the quotations after pinecone_index_name and ID. Sorry can't be much more help right now.

**Comment by mberman84** [comment]
> > I'm still getting this error as well. I cloned the repo everyone is talking about, then I upgraded the pinecone version to 0.0.1.2, and am using node ~18. I'm getting this error:
> > error [ErrorWithoutStackTrace: PineconeClient: Error getting project name: SyntaxError: Unexpected token A in JSON at position 0]
> > /Users/matthewberman/Desktop/gpt4-pdf-chatbot-langchain/utils/pinecone-client.ts:19
> > ```
> > throw new Error('Failed to initialize Pinecone Client');
> > ```
> 
> Did you try adding the project # in the pinecone.ts? Project number a weird hash like '13h5ja' before the -gcp-1-east or whatever. Not near a computer so don't have a snapshot of my example. The one used has it after the quotations after pinecone_index_name and ID. Sorry can't be much more help right now.

Not sure I understand. Here's what I have:

```
if (!process.env.PINECONE_INDEX_NAME) {
  throw new Error('Missing Pinecone index name in .env file');
}

const PINECONE_INDEX_NAME = process.env.PINECONE_INDEX_NAME ?? '';

const PINECONE_NAME_SPACE = 'pdfchat-abf53ba'; //namespace is optional for your vectors

export { PINECONE_INDEX_NAME, PINECONE_NAME_SPACE };
```

**Comment by dyeoman2** [comment]
I was able to solve this problem by setting the project name after the init. Here is the code that worked for me. 

I'm using Node v19.8.1, "langchain": "^0.0.45", and "@pinecone-database/pinecone": "^0.0.10".

```
import { PineconeClient } from '@pinecone-database/pinecone';

if (!process.env.PINECONE_ENVIRONMENT || !process.env.PINECONE_API_KEY) {
  throw new Error('Pinecone environment or api key vars missing');
}

async function initPinecone() {
  try {
    const pinecone = new PineconeClient();

    await pinecone.init({
      environment: process.env.PINECONE_ENVIRONMENT ?? '', //this is in the dashboard
      apiKey: process.env.PINECONE_API_KEY ?? '',
    });
    pinecone.projectName = 'default';

    return pinecone;
  } catch (error) {
    console.log('error', error);
    throw new Error('Failed to initialize Pinecone Client');
  }
}

export const pinecone = await initPinecone();
```

**Comment by felipeotarola** [comment]
I also did the  project name  workaround at first, but after some digging I understood that my environments were written wrong.
here is a template.

![image](https://user-images.githubusercontent.com/5517674/229460701-d151d112-8f28-4c7f-bfff-bd3c4a3c4f27.png)
PINECONE_ENVIRONMENT="eu-west1-gcp"
PINECONE_INDEX_NAME="indexname"
PINECONE_API_KEY = "0000000-0000-42a9-901b-123456788"

**Comment by kaleyroy** [comment]
My node version: v18.12.1
and **downgrade to version** @pinecone-database/pinecone": "^0.0.10  
Fixed the problem

**Comment by ijot-nl** [comment]
I experienced this error, when the 'environment' was incorrectly set in the call to init().
I had 'us-east-gcp'. Should have been: 'us-east1-gcp'...
Strange that the init() call did not fail, but that the error was generated from the subsequent call.

**Comment by felipe1120gomez** [comment]
Update to version 0.0.12 and move to another wi-fi network to avoid problems with a proxy worked for me

**Comment by premgadwal** [comment]
> hiya new to pinecone, am also having the same errors.
> 
> To recreate-- I cloned the repo from : https://github.com/mayooear/gpt4-pdf-chatbot-langchain && inputted my own API keys for OpenAI and PineCone. I've confirmed that my API keys work for both because when I removed them individually, I receive the expected corresponding errors of needing respective keys.
> 
> @rschwabco I am running Node 19.7, and I've tried updating my pinecone to 0.0.10 and 0.0.12 and both are returning below:
> 
> PineconeClient: Error getting project name: TypeError: fetch failed [Error: PineconeClient: Project name not set. Call init() first.]

is it solved?

**Comment by mjrussell91** [comment]
> I also did the project name workaround at first, but after some digging I understood that my environments were written wrong. here is a template.
> 
> ![image](https://user-images.githubusercontent.com/5517674/229460701-d151d112-8f28-4c7f-bfff-bd3c4a3c4f27.png) PINECONE_ENVIRONMENT="eu-west1-gcp" PINECONE_INDEX_NAME="indexname" PINECONE_API_KEY = "0000000-0000-42a9-901b-123456788"

This is correct and fixed the issue for me. Perhaps the .env.example in this repo (https://github.com/mayooear/gpt4-pdf-chatbot-langchain) should be updated to reflect this.

**Comment by DigitalSolomon** [comment]
> I also did the project name workaround at first, but after some digging I understood that my environments were written wrong. here is a template.
> 
> ![image](https://user-images.githubusercontent.com/5517674/229460701-d151d112-8f28-4c7f-bfff-bd3c4a3c4f27.png) PINECONE_ENVIRONMENT="eu-west1-gcp" PINECONE_INDEX_NAME="indexname" PINECONE_API_KEY = "0000000-0000-42a9-901b-123456788"

What was written wrong previously re: the environment? Is the correct approach just to copy the exact string displayed in the Pinecone UI in the `Environment` column? Because that's what I'm doing and I still get the error. Curious if there were any more subtleties hiding there.

**Comment by mjrussell91** [comment]
> > I also did the project name workaround at first, but after some digging I understood that my environments were written wrong. here is a template.
> > ![image](https://user-images.githubusercontent.com/5517674/229460701-d151d112-8f28-4c7f-bfff-bd3c4a3c4f27.png) PINECONE_ENVIRONMENT="eu-west1-gcp" PINECONE_INDEX_NAME="indexname" PINECONE_API_KEY = "0000000-0000-42a9-901b-123456788"
> 
> What was written wrong previously re: the environment? Is the correct approach just to copy the exact string displayed in the Pinecone UI in the `Environment` column? Because that's what I'm doing and I still get the error. Curious if there were any more subtleties hiding there.

Correct: PINECONE_INDEX_NAME="indexname"
Incorrect: PINECONE_INDEX_NAME="indexname-f15gc52.svc.eu-west1-gcp.pinecone.io"

Just try setting it as the first part of the Index Name column, not the whole string. Environment should be fine to be copied as is.

**Comment by liugod** [comment]
I found that every index have a diffrent apikey,so if you have two or more index and you only set one apikey,you will get the "bug"

**Comment by richard523** [comment]
> I was able to solve this problem by setting the project name after the init. Here is the code that worked for me.
> 
> I'm using Node v19.8.1, "langchain": "^0.0.45", and "@pinecone-database/pinecone": "^0.0.10".
> 
> ```
> import { PineconeClient } from '@pinecone-database/pinecone';
> 
> if (!process.env.PINECONE_ENVIRONMENT || !process.env.PINECONE_API_KEY) {
>   throw new Error('Pinecone environment or api key vars missing');
> }
> 
> async function initPinecone() {
>   try {
>     const pinecone = new PineconeClient();
> 
>     await pinecone.init({
>       environment: process.env.PINECONE_ENVIRONMENT ?? '', //this is in the dashboard
>       apiKey: process.env.PINECONE_API_KEY ?? '',
>     });
>     pinecone.projectName = 'default';
> 
>     return pinecone;
>   } catch (error) {
>     console.log('error', error);
>     throw new Error('Failed to initialize Pinecone Client');
>   }
> }
> 
> export const pinecone = await initPinecone();
> ```

Current working solution for me!

**Comment by shawnesquivel** [comment]
I'm still getting this error with the prescribed workarounds by @richard523  and @dyeoman2  -- please let me know if anyone else has any recommendations! 

Context
- Verified my env key was being passed in correctly, as mentioned by others`us-east-1`
- I'm using one of the new serverless indexes (still has the environment mentioned above) but I wonder if this solution is incompatible with serverless indexes...
