### ISSUE TITLE
[Bug] sorry this is wrong.

### ISSUE THREAD

**Issue by toypilot** [pinecone-io/pinecone-ts-client#121]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

this is v1.0.1 pinecone node lib
PineconeClient is deprecated after v1.0.0
![image](https://github.com/pinecone-io/pinecone-ts-client/assets/6387384/7c9bb78a-7276-4116-8f69-b1bd65f61e29)

pineconeIndex in PineconeLibArgs must be changed.

### Expected Behavior

I want to create PineconeStore object without any errors.

### Steps To Reproduce

1. langchain": "^0.0.150
2. @pinecone-database/pinecone": "^1.0.1
3. create PineconeStore class object.

### Environment

```markdown
- **OS**: windows
- **Language version**: node.js
- **Pinecone client version**: 1.0.1
```

**Comment by toypilot** [comment]
I am sorry. I write wrong place. how can I remove this issue?

**Comment by jhamon** [comment]
I'll close it. Let us know if it's something we can help with something in this module.
