### ISSUE TITLE
[Bug] Docs link appears to be broken

### ISSUE THREAD

**Issue by freddieb** [pinecone-io/pinecone-ts-client#149]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The 'Reference Documentation' button does not appear to work (get a Github pages 404) https://www.npmjs.com/package/@pinecone-database/pinecone#pinecone-nodejs-client-----

### Expected Behavior

Link works

### Steps To Reproduce

1. Go to the [NPM package page](https://www.npmjs.com/package/@pinecone-database/pinecone#pinecone-nodejs-client-----)
2. 2. Click the link '[Reference Documentation](https://pinecone-io.github.io/pinecone-ts-client/classes/Pinecone.html)'

### Environment

```markdown
- **OS**:
- **Language version**:
- **Pinecone client version**:
```

**Comment by austin-denoble** [comment]
Thanks for reporting. We recently updated the domain that hosts our reference documentation, and missed updating the README link. I've opened a PR to get that cleaned up: #https://github.com/pinecone-io/pinecone-ts-client/pull/150.

In the meantime, you can find the reference docs at this address: https://sdk.pinecone.io/typescript/classes/Pinecone.html
