### ISSUE TITLE
How to use in Node.js

### ISSUE THREAD

**Issue by DoctorSlimm** [pinecone-io/pinecone-ts-client#15]
How to use this package in a node.js enviroment? without setting type: module in package.json as I have other packages which will not work in that case.

```const { PineconeClient } = "@pinecone-database/pinecone";```  does not work either and results in the error: 

```const pineconeClient = new PineconeClient();
                           ^

TypeError: PineconeClient is not a constructor```

**Comment by rico0610** [comment]
This is how I do it.

const Pinecone = require("@pinecone-database/pinecone");
const pinecone = new Pinecone.PineconeClient();
