### ISSUE TITLE
[Bug] `describeIndexStats` doesn't take argument `DescribeIndexStatsOptions`

### ISSUE THREAD

**Issue by douglasqian** [pinecone-io/pinecone-ts-client#152]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently in the latest version of the SDK (1.1.2) no arguments to this function are supported even though the docs say that you can use filters (and this is how it used to work as well so IMO this is a regression).

### Expected Behavior

Support argument of type `DescribeIndexStatsOptions` as they appear here in the docs:
https://sdk.pinecone.io/typescript/types/DescribeIndexStatsOptions.html

### Steps To Reproduce

Try to use `describeIndexStats`

### Environment

```markdown
- **OS**:
- **Language version**:
- **Pinecone client version**:
```

**Comment by anawishnoff** [comment]
Closing as this is stale - please reopen if you're still facing this issue. Thanks!
