### ISSUE TITLE
[Bug] @pinecone-database/pinecone supports node >=14 but its dependency required node >=16

### ISSUE THREAD

**Issue by hotuansang96** [pinecone-io/pinecone-ts-client#156]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

yarn install got an error:

```bash
error @edge-runtime/types@2.2.7: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.21.3"
error Found incompatible module.
```

### Expected Behavior

Can install @pinecone-database/pinecone ^1.1.2 in node version 14

### Steps To Reproduce

Use node v14.21.3
Install @pinecone-database/pinecone ^1.1.2

### Environment

```markdown
- **OS**: MacOS
- **Language version**: Node 14.21.3
- **Pinecone client version**: ^1.1.2
```

**Comment by anawishnoff** [comment]
Closing as this issue is stale. Apologies for the lack of response, please feel free to reopen if you are still having issues.
