### ISSUE TITLE
PineconeClient: Error calling upsert

### ISSUE THREAD

**Issue by mayooear** [pinecone-io/pinecone-ts-client#16]
The error below occurs whenever `index.upsert` is run, even using the example provided in the doc.

code: 
```
const upsertResponse = await index.upsert({
      upsertRequest: {
        vectors: [
          {
            id: "vec1",
            values: [0.1, 0.2, 0.3, 0.4],
            metadata: {
              genre: "drama",
            },
          },
          {
            id: "vec2",
            values: [0.1, 0.2, 0.3, 0.4],
            metadata: {
              genre: "comedy",
            },
          },
        ],
        namespace: "example-namespace",
      },
    });
```

Error log:
```
PineconeClient: Error calling upsert: PineconeClient: Error calling upsertRaw: ResponseError: Response returned an error code  econeClient: Error calling upsertRaw: ResponseError: Response returned an error code
```

**Comment by rico0610** [comment]
This works for me.

const toUpsert = some data 

const upsertResponse = await index.upsert(
            {
              vectors: toUpsert,
            }
            )

**Comment by mayooear** [comment]
Strange. Your syntax doesn't correspond with the latest version types. What version are you using?

```
const upsertResponse = await index.upsert({
    upsertRequest: {
          vectors: [
              {
                 id:
```

**Comment by sbusso** [comment]
Got the same error message `ResponseError: Response returned an error code` with `createIndex`, error messages are not helpful. I'd think the ts-client is not aligned with the api

**Comment by mayooear** [comment]
> Got the same error message `ResponseError: Response returned an error code` with `createIndex`, error messages are not helpful. I'd think the ts-client is not aligned with the api

I tested the endpoint via Postman and noticed the error code was related to a mismatch between vector dimensions set for the index on the dashboard and the number of vector dimensions upserted.

In essence, you need to upsert the same number of vector dimensions.

**Comment by rico0610** [comment]
> 

Yes, if you're using openAI's text embedding, 1536 should be the dimension you'll have to use for the vector

**Comment by rico0610** [comment]
> Strange. Your syntax doesn't correspond with the latest version types. What version are you using?
> 
> ```
> const upsertResponse = await index.upsert({
>     upsertRequest: {
>           vectors: [
>               {
>                  id:
> ```

I'm using the same version. Here's my code:

```
const toUpsert = batchRows.map((row, j) => {
            return {
              id: uuidv4(),
              values: embeddings[j],
              metadata: {
                NOTES: Object.values(row)[0],
              },
            };
          });

          const upsertResponse = await index.upsert(
            {
              vectors: toUpsert,
            },
            {
              timeout: 120000, // set timeout to 120 seconds
            }
          );

```

**Comment by ceednee** [comment]
Following the documentation, this simple code is not working.
I truly don't understand how to make this client work

```bash
PineconeClient: Error calling upsertRaw: FetchError: The request failed and 
the interceptors did not return an alternative response
```

```js
 const index = client.Index(String(process.env.PINECONE_NAMESPACE));

  const vector1 = {
    id: 'vec1',
    values: [0.1, 0.2, 0.3, 0.4],
    metadata: { genre: 'drama' },
  };

  const vector2 = {
    id: 'vec2',
    values: [0.2, 0.3, 0.4, 0.5],
    metadata: { genre: 'action' },
  };

  const upsertRequest = {
    vectors: [vector1, vector2],
    namespace,
  };

 await index.upsert({ upsertRequest }).catch((error) => {
    console.error(error);
  });
```

**Comment by rschwabco** [comment]
@ceednee what dimensions are you using in this index?

**Comment by felipetodev** [comment]
Did anyone manage to make the client work?   `@pinecone-database/pinecone: ^0.0.10 `  🤦‍♂️

**Comment by rschwabco** [comment]
@felipetodev I'm using it every day. Do you have a particular issue?

**Comment by maxtechera** [comment]
This has been working for me for the past few days and suddenly stopped showing good error messages. I'm sure the underlying error is something in my embeddings. 
But previous version would show the full error, since the signature changed the error messaging became much more vague.

**Comment by mayooear** [comment]
> Did anyone manage to make the client work? `@pinecone-database/pinecone: ^0.0.10 ` 🤦‍♂️

I'm having issues with this alongside LangChain. But as discussed @rschwabco it's probably related to the upsert function that doesn't factor in the 100 chunk size Pinecone limit.

**Comment by rschwabco** [comment]
@maxtechera we had an issue prior to 0.0.10 which caused the error message to not be relayed back from the API. Can you confirm that you are using 0.0.10, and give more information regarding the call you're making and error you're getting?

**Comment by Hesse** [comment]
I haven't been able to get this going. I have increased the dimension to 1536 (to match OpenAPI limits) and have experimented modifying the chunk and overlap size but to no avail. I keep getting this error. Any ideas? @mayooear I'm actually running into this issue following your tutorial.

**Comment by Hesse** [comment]
> I haven't been able to get this going. I have increased the dimension to 1536 (to match OpenAPI limits) and have experimented modifying the chunk and overlap size but to no avail. I keep getting this error. Any ideas? @mayooear I'm actually running into this issue following your tutorial.

I was able to resolve this issue by deleting the project and re-creating it in different region (Canada). You will also need to retrieve a new API key when doing this. 

The initial region that was causing issues was Asia.

**Comment by esponges** [comment]
> > I haven't been able to get this going. I have increased the dimension to 1536 (to match OpenAPI limits) and have experimented modifying the chunk and overlap size but to no avail. I keep getting this error. Any ideas? @mayooear I'm actually running into this issue following your tutorial.
> 
> I was able to resolve this issue by deleting the project and re-creating it in different region (Canada). You will also need to retrieve a new API key when doing this.
> 
> The initial region that was causing issues was Asia.

I'm experimenting the same issue, and I'm in Asia too. So you basically mean deleting the index and creating a new one with a different `environment`?

**Comment by altaf53** [comment]
Have anyone able to resolve this issue ? I am still facing it and not able to resolve. I am using OpenAI and have configured dimension on pincone dashoboard as 1536. I am referring langchain docs for igestion of my documents below is my code 
`await PineconeStore.fromDocuments(
          batch,
          new OpenAIEmbeddings({
            openAIApiKey: process.env.OPEN_API_KEY,
            temperature: 0.9,
          }),

          { pineconeIndex }
        );`

Any help will be appreciated
