### ISSUE TITLE
[Bug] The v1 fetch request hangs when you pass in more than 1 vector ID

### ISSUE THREAD

**Issue by andrewrgabb-sauce** [pinecone-io/pinecone-ts-client#163]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The v1 fetch request hangs when you pass in more than 1 vector ID. (and yes, this is a paid namespace)

This works: 
`const fetchResult = await namespace.fetch(['id1']);`

This hangs:
`const fetchResult = await namespace.fetch(['id1', 'id2']);`

### Expected Behavior

I expect the request to respond with the appropriate results.

### Steps To Reproduce

```
const client = new Pinecone({
      apiKey: 'apiKey',
      environment: 'environment',
});

const index = client.index('indexName');

const namespace = index.namespace('nameSpace');

const fetchResult = await namespace.fetch(['id1', 'id2']);
```

### Environment

```markdown
- **OS**: MacOS Ventura 13.5.1
- **Language version**: Node 18
- **Pinecone client version**: 1.1.2
```

**Comment by ederelk** [comment]
I am also running into this issue. but it works well on my Mac. but on our linux prod env it hangs

**Comment by anawishnoff** [comment]
As this issue is from last year, I'll go ahead and close this as stale. However please feel free to reopen or file a new issue if you're still having issues - thank you!

**Comment by Josecodesalot** [comment]
happened for me today
