### ISSUE TITLE
PineconeClient: Error getting project name: ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by secoldPrivate** [pinecone-io/pinecone-ts-client#17]
Wierd error.

I thought it was because node was not v18 or higher, but even after the updating it still fails like this.

![image](https://user-images.githubusercontent.com/32119564/222389752-7cb4ad10-62d6-416c-92e6-20afd26f1467.png)

Everything else is configured correctly and not throwing any errors. Just that upsert fails.

**Comment by secoldPrivate** [comment]
Odd thing is the index is actually created.

**Comment by rschwabco** [comment]
This should be solve by #13
