### ISSUE TITLE
Dev dependencies listed as dependencies

### ISSUE THREAD

**Issue by SalmonMode** [pinecone-io/pinecone-ts-client#174]
It looks like the following packages are listed as dependencies, but can be moved to devDependencies:

- @edge-runtime/types
- @types/node
- typescript

This would help immensely reduce the size of the package after installing, as npm will install these inside the package folder under a nested node_modules folder if the parent package doesn't have a compatible version. Since TypeScript itself isn't really used during runtime of most node apps (and TypeScript 5 is now available), this results in an extra ~80 MB being taken up.

I noticed this because I'm using the client in an AWS lambda layer and it made the lambda layer too big to be uploaded for use. Luckily, these packages should only be needed for compilation, so there shouldn't be any complications from moving them to devDependencies.

**Comment by austin-denoble** [comment]
Good catch, thank you for contributing!
