### ISSUE TITLE
Unclear query parameters

### ISSUE THREAD

**Issue by bestfizzz** [pinecone-io/pinecone-ts-client#18]
`const query_pinecone = async (encodedQuery, top_k = 1) => {
  try {
    await pinecone.init({
      environment: environment,
      apiKey: apiKey,
    })
    const index = pinecone.Index(projectName)
    const xc = await index.query({
      topK: top_k,
      vector:encodedQuery,
      includeMetadata : true
    })
    return xc
  } catch (err) {
    console.log(err)
  }
}`

From the doc,  it seems like the only two required params are topK and vector. But keep getting this error: 
PineconeClient: Error calling query: PineconeClient: Error calling queryRaw: RequiredError: Required parameter requestParameters.queryRequest was null or undefined when calling query.

**Comment by sammyjava** [comment]
I'm getting something similar:
```
Error: PineconeClient: Error calling query: Error: PineconeClient: Error calling queryRaw: FetchError: The request failed and the interceptors did not return an alternative response
```
But this follows what looks to be a problem with API authentication; I get a 401 back with this:
```
www-authenticate | API key is missing or invalid for the environment "us-west1-gcp". Check that the correct environment is specified.
```
It seems like PineconeClient.Index.query is not passing the API key. But I don't see how to make it do so. And I'm not sure my QueryRequest cast is working, although it looks decent when spit out to the console:
```
{
  "topK": 10,
  "includeMetadata": true,
  "encodedQuery": [
    -0.0019221940310671926,
    -0.03103446587920189,
    ...
   -0.004857071675360203,
    -0.007041166536509991,
    -0.015199776738882065
  ]
}
```

**Comment by gdj0nes** [comment]
@bestfizzz @sammyjava are you still seeing issues with this?

**Comment by bestfizzz** [comment]
@gdj0nes I make a http request instead.

**Comment by sammyjava** [comment]
Again, if you could post or point me to a piece of code that *works* for you, I'd love to try it! I have yet to see any code that works using this package. The tests fail, and I've not seen a working example anywhere.

**Comment by rschwabco** [comment]
@sammyjava as an additional example of a use of this package in the wild, please see [Langchain JS](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/vectorstores/pinecone.ts), which is widely used with no issues.

**Comment by sammyjava** [comment]
Thanks. I see classes and methods, but I still do not see a working front-to-back example app that uses this stuff. What I mean is an app that loads in the browser and works. Am I missing something?

**Comment by rschwabco** [comment]
@sammyjava to be very clear, this package is not intended to work in the browser but rather run in Node.js. If you'd like, you can [email me](mailto:roie.s.c@pinecone.io) and I can attempt to assist you further.
