### ISSUE TITLE
[Bug] v2.0.0 doesn't seem to work with serverless

### ISSUE THREAD

**Issue by stephenkalnoske-sans** [pinecone-io/pinecone-ts-client#194]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After reading the docs, when I pass along an API key in the Pinecone constructor, it yells at me and tells me it needs an environment. Using us-west-2 does not work as the environment. This is not talked about in any of the documentation.

### Expected Behavior

It should work and query results.

### Steps To Reproduce

Using the pinecone index.query method. and the new Pinecone({}) constructor.

### Relevant log output

```shell
{
    "errorType": "PineconeConfigurationError",
    "errorMessage": "Since you called 'new Pinecone()' with no configuration object, we attempted to find client configuration in environment variables but the required environment variables were not set. Missing variables: PINECONE_ENVIRONMENT. You can find the configuration values for your project in the Pinecone developer console at https://app.pinecone.io"
......
```

### Environment

```markdown
- **OS**:
- **Language version**:
- **Pinecone client version**:
```

**Comment by christianlovescode** [comment]
What was your solution here? Running into the same problem
