### ISSUE TITLE
Documentation not clear to to upsert... 

### ISSUE THREAD

**Issue by ljs19923** [pinecone-io/pinecone-ts-client#20]
I don't understand your documentation... Your doc on github is different than your doc on website, who is different than your API reference on your website...

I'm not able to upsert vectors, can you give me the good code please. I got errors.

Clean all of your docs please.. sometimes in you website some "}" are missing too. Sometime you write ".index" instead ".Index"

Thanks a lot

` const vector1 = {
      id: "vec1",
      values: [0.1, 0.2, 0.3, 0.4],
      metadata: { genre: "drama" },
    };

    const vector2 = {
      id: "vec2",
      values: [0.2, 0.3, 0.4, 0.5],
      metadata: { genre: "action" },
    };

    var vectors = [vector1, vector2];
    const upsertRequest = {
      vectors: vectors,
    };
    await index.upsert({ upsertRequest });`

**Comment by ceednee** [comment]
Same here ...

I used the tests to understand and try to make 'upsert' work.
Unfortunately, upsert function doesn't work and the documentation is not help at all.

Can you give us a working example please?

**Comment by lewisbamboo** [comment]
This format works for me. Same for query. Have to wrap in queryRequest: {}

`index.upsert({
    upsertRequest: {
        vectors : [
            {
                id: VECTOR_ID,
                values: VECTOR_VALUES,
                metadata: {
                    KEY: VALUE,
                }
            }
        ],
        namespace: INDEX_NAMESPACE
    }
})
`
