### ISSUE TITLE
[Feature] I want to ask when to release next version

### ISSUE THREAD

**Issue by le0zh0u** [pinecone-io/pinecone-ts-client#205]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

I need to use `List Record IDs` function.

It has been added into [Pinecone TypeScript SDK - v2.0.1](https://sdk.pinecone.io/typescript/). But this is not in the latest release package.

**Comment by austin-denoble** [comment]
Hey @le0zh0u, `v2.1.0` has been released which includes the List Record IDs functionality: https://github.com/pinecone-io/pinecone-ts-client/releases/tag/v2.1.0.

Thanks for flagging, the client reference documentation was updated prematurely.
