### ISSUE TITLE
PineconeInternalServerError: An internal server error occurred while calling the describe_index_stats endpoint

### ISSUE THREAD

**Issue by coderabbit-amank** [pinecone-io/pinecone-ts-client#208]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Our service is calling describeIndexStats() function which is getting failed after some duration. I searched and found there is one mention but not any reply on this thread as well. https://community.pinecone.io/t/an-internal-server-error-occured-while-calling-the-endpoint/4499

Please help 
<img width="1492" alt="image" src="https://github.com/pinecone-io/pinecone-ts-client/assets/151006737/33b8f72f-2d19-413a-889d-8dd53dc9e433">

### Expected Behavior

This should not occur when getting index stats.

### Steps To Reproduce

1. In the GCP cloud run with : Ubuntu 20.04
2. With node:21-slim
3. with Pinecone TS client pinecone-database/pinecone 1.1.2

### Relevant log output

```shell
Error getting index stats PineconeInternalServerError: An internal server error occured while calling the https://issues-003-large-429ed45.svc.apw5-4e34-81fa.pinecone.io/describe_index_stats endpoint. To see overall service health and learn whether this seems like a large-scale problem or one specific to your request, please go to https://status.pinecone.io/ to view our status page. If you believe the error reflects a problem with this client, please file a bug report in the github issue tracker at https://github.com/pinecone-io/pinecone-ts-client
```

### Environment

```markdown
- **GCP Cloud Run Ubuntu 20.04**:
- **node:21-slim**:
- **@pinecone-database/pinecone": "^1.1.2**:
```

**Comment by anawishnoff** [comment]
@coderabbit-amank Are you still hitting this issue?
