### ISSUE TITLE
[Feature] Export `ListResponse` type

### ISSUE THREAD

**Issue by MikeCarbone** [pinecone-io/pinecone-ts-client#209]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

When incorporating the delete function using the new serverless API, I needed access to the `ListResponse` type for this function, which will recursively delete all vectors related to a source document:

```js
async function deletePineconePage(page: ListResponse) {
  if (page.vectors) {
    const pageVectorIds = page.vectors.map((vector) => vector.id);
    await index.deleteMany(pageVectorIds);
    if (page?.pagination?.next) {
      const nextPage = await index.listPaginated({
        prefix: `source_${sourceId}#`,
        paginationToken: page.pagination.next,
      });
      return await deletePineconePage(nextPage);
    }
  }
}
const initialPage = await index.listPaginated({
  prefix: `source_${sourceId}#`,
});
await deletePineconePage(initialPage);
```

### Describe alternatives you've considered

Unfortunately, that `ListResponse` type is not exported from the main package. Instead I had to import the type from the build:
```js
import type { ListResponse } from "@pinecone-database/pinecone/dist/pinecone-generated-ts-fetch";
```

### Who will this benefit?

Anyone trying to access the type after using the new `index.listPaginated` option

### Are you interested in contributing this feature?

No

**Comment by austin-denoble** [comment]
Thank you for flagging, this interface should have been exported from the top level of the package. `v2.1.1` exports the interface. You can find details here: https://github.com/pinecone-io/pinecone-ts-client/releases/tag/v2.1.1

**Comment by MikeCarbone** [comment]
Great! Thanks @austin-denoble !
