### ISSUE TITLE
[Bug] PineconeInternalServerError while trying to access upsert

### ISSUE THREAD

**Issue by craigloewen-msft** [pinecone-io/pinecone-ts-client#211]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Trying to call the 'upsert' code to upsert a new embedding into Pinecone but it's failing.

Ther error being seen is:
```
PineconeInternalServerError: An internal server error occured while calling the REDACTED-starter.pinecone.io/vectors/upsert endpoint. To see overall service health and learn whether this seems like a large-scale problem or one specific to your request, please go to https://status.pinecone.io/ to view our status page. If you believe the error reflects a problem with this client, please file a bug report in the github issue tracker at https://github.com/pinecone-io/pinecone-ts-client\n    at mapHttpStatusError (/workspace/node_modules/@pinecone-database/pinecone/dist/errors/http.js:187:20)\n    at /workspace/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:65:69\n    at step (/workspace/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:33:23)\n    at Object.next (/workspace/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:14:53)\n    at fulfilled (/workspace/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

It seems like a production or client issue, but the production tracker link shows green.

And here is the line where we are calling it:
https://github.com/craigloewen-msft/GitGudIssues/blob/d4c44bc08600b638b047c2bd377b81441146d745/backendsrc/embeddingsHandler.js#L50

### Expected Behavior

The upsert request should behave as it did before. We didn't make any code changes from this working to failing, so it seems like a server issue.

### Steps To Reproduce

1. Make a pinecone index
2. Call upsert into it.

### Environment

```markdown
- **OS**: Ubuntu 20.04
- **Language version**: Node.JS v18
- **Pinecone client version**: "@pinecone-database/pinecone": "^1.1.2",
```

**Comment by craigloewen-msft** [comment]
@plante-msft for visibility

**Comment by anawishnoff** [comment]
@craigloewen-msft First of all, hi Craig!! Long time since working together at Microsoft :) 

Secondly are you still seeing this issue?

**Comment by vivek-alhat** [comment]
I am facing the same issue with the exact same version. Sometimes it works correctly and data is upserted into the index but often I see below error:
`Error: An internal server error occured while calling the https://indexname.svc.gcp-starter.pinecone.io/vectors/upsert endpoint. To see overall service health and learn whether this seems like a large-scale problem or one specific to your request, please go to https://status.pinecone.io/ to view our status page. If you believe the error reflects a problem with this client, please file a bug report in the github issue tracker at https://github.com/pinecone-io/pinecone-ts-client`

 **Pinecone client version**: "@pinecone-database/pinecone": "^1.1.2"

**Comment by anawishnoff** [comment]
Hey @vivek-alhat - I'd recommend first updating to the latest version of the client, it's been updated a few times since the one you're using. If you're still seeing this issue in the updated version, we'll be able to investigate more thoroughly
