### ISSUE TITLE
[Bug] issue with deps `@sinclair+typebox`

### ISSUE THREAD

**Issue by nicolasburtey** [pinecone-io/pinecone-ts-client#212]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

can you update `@sinclair+typebox`

current version has issue I'm running into

```
../../node_modules/.pnpm/@sinclair+typebox@0.29.6/node_modules/@sinclair/typebox/typebox.d.ts:179:306 - error TS2589: Type instantiation is excessively deep and possibly infinite.

179 export type TIndex<T extends TSchema, K extends Key[]> = T extends TRecursive<infer S> ? TIndex<S, K> : T extends TIntersect ? UnionType<Flat<TIndexRestMany<T, K>>> : T extends TUnion ? UnionType<Flat<TIndexRestMany<T, K>>> : T extends TObject ? UnionType<Flat<TIndexRestMany<T, K>>> : T extends TTuple ? UnionType<Flat<TIndexRestMany<T, K>>> : TNever;
```                                                                                                                       

documented here https://github.com/sinclairzx81/typebox/issues/737                                                                                                                                                                   

### Expected Behavior

pass typescript check

### Steps To Reproduce

-

### Environment

```markdown
- **OS**:
- **Language version**:
- **Pinecone client version**:
```

**Comment by guinaut** [comment]
Not much to add.. also seeing this issue.

**Comment by hstanford** [comment]
I've resolved this by overriding the dependency to the latest (`0.32.30` at the time of writing). For pnpm, top level in package.json:
```
  "pnpm": {
    "overrides": {
      "@pinecone-database/pinecone>@sinclair/typebox": "0.32.30"
    }
  }
```

Typescript version 5.4.5

**Comment by anawishnoff** [comment]
Hi all, closing out this issue as it seems to have been resolved. Please feel free to reopen if needed.
