### ISSUE TITLE
[Bug] Can't initialize client on nodejs

### ISSUE THREAD

**Issue by Ilikepizza2** [pinecone-io/pinecone-ts-client#217]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In nodejs, even when initilizing client I get a timeout error indicating service is down. However I can very well access it from the frontend, using curl, or the python client. I've made sure that it can read the api key in the env. I had used the same code before and it was working.

![image](https://github.com/pinecone-io/pinecone-ts-client/assets/95919665/05b02cc5-d740-4277-a69f-8899dfb82df8)
![image](https://github.com/pinecone-io/pinecone-ts-client/assets/95919665/f62761d7-986c-487d-804d-3777a9947000)

### Expected Behavior

The client should be initialized properly

### Steps To Reproduce

1. Put api key in .env
2. Here's my code ->
```node
const { Pinecone } = require('@pinecone-database/pinecone');
require("dotenv").config();

const f = async () => {
    try {
        const pc = new Pinecone();
        console.log(await pc.listIndexes());
    } catch (e) {
        console.log("error", e);
    }
}

f();
```

### Environment

```markdown
- **OS**: Linux Mint
- **Language version**: v21.6.1
- **Pinecone client version**: v2.2.1
```

**Comment by anawishnoff** [comment]
Hey @Ilikepizza2 , are you still facing this issue? Apologies for the delayed response to your issue.
