### ISSUE TITLE
Your request is larger than the maximum supported size - 2MB. Please try to reduce your batch size.

### ISSUE THREAD

**Issue by rico0610** [pinecone-io/pinecone-ts-client#23]
Encountered the following error when trying to upserting 753 items:

Your request is larger than the maximum supported size - 2MB. Please try to reduce your batch size.

**Comment by rico0610** [comment]
When updating it to aroun 54 vectors only, I'm getting this:

    status: 503,
    statusText: 'Service Unavailable'

**Comment by rschwabco** [comment]
You will most likely have to chunk your upserts such that each chunk is no bigger than 2mb. Can you give more details regarding the 503? It's unclear to me what may cause this other than network disruptions.
