### ISSUE TITLE
long term support

### ISSUE THREAD

**Issue by siddhantx0** [pinecone-io/pinecone-ts-client#233]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

would love lts for existing tooling and data lakes like Snowflake etc.

### Describe alternatives you've considered

opensource

### Who will this benefit?

siddhantx0

### Are you interested in contributing this feature?

would love to help lts coding if needed --> email siddhantx0@gmail.com

### Anything else?

siddhantx0.com 
siddhantx0.com 
siddhantx0.com 
siddhantx0.com 
siddhantx0.com 
siddhantx0.com 
siddhantx0.com 
siddhantx0.com

**Comment by anawishnoff** [comment]
Closing due to lack of detail in this issue, please reopen with more details if needed
