### ISSUE TITLE
Jest unable to print out test message when importing this library

### ISSUE THREAD

**Issue by Tae69** [pinecone-io/pinecone-ts-client#24]
Steps to reproduce:
```typescript
import { PineconeClient } from "@pinecone-database/pinecone";

it("test", () => {
  const pinecone = new PineconeClient();
  expect("a").toBe("b");
});
```

Expected:
Jest should show
```
expect(received).toBe(expected) // Object.is equality

    Expected: "b"
    Received: "a"
```

Received:
Empty log

I saw that the library is replacing `Error.prepareStackTrace` with empty function, which caused this issue.
https://github.com/pinecone-io/pinecone-ts-client/blob/main/src/index.ts#L10

**Comment by rschwabco** [comment]
This was addressed in #27.
