### ISSUE TITLE
[Bug] tsconfig: remove dependency on "dom" types

### ISSUE THREAD

**Issue by mpareja** [pinecone-io/pinecone-ts-client#251]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The [`tsconfig` used by this project](https://github.com/pinecone-io/pinecone-ts-client/blob/main/tsconfig.json#L5) allows your code to reference `dom` types. Doing so causes problems for end-users since the library is intended to be run server-side only.

Our server projects intentionally do not make `dom` types available, so we're unable to use your client library. Compilation fails when encountering DOM type-references in Pinecone code, like `RequestCredentials` and `WindowOrWorkerGlobalScope` in `runtime.d.ts`.

### Expected Behavior

Avoid publishing code that couples to DOM types when the library is intended to run in Node.js.

### Steps To Reproduce

Tested with Node.js LTS (20).

```bash
$ npm i @pinecone-database/pinecone typescript @types/node@^20

$ npm ls 
p@ /tmp/p
├── @pinecone-database/pinecone@3.0.0
├── @types/node@20.16.1
└── typescript@5.5.4

$ npx tsc
node_modules/@pinecone-database/pinecone/dist/pinecone-generated-ts-fetch/control/runtime.d.ts:23:19 - error TS2304: Cannot find name 'RequestCredentials'.

23     credentials?: RequestCredentials;

... on and on ...
```

tsconfig.json:
```json
{
  "compilerOptions": {
    // target node 20 (https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping)
    "lib": ["ES2023"],
    "module": "node16",
    "target": "ES2022",

    "declaration": true,
    "strict": true,
    "outDir": "build",
    "baseUrl": "./",
    "rootDir": "src",
    "esModuleInterop": true
  }
}
```

src/index.ts:

```ts
import { Pinecone } from '@pinecone-database/pinecone'

export function foo(pinecone: Pinecone) {
  console.log(pinecone)
}
```

### Environment

```markdown
- OS: Ubuntu 23.10
- Node.js 20


$ npm ls 
p@ /tmp/p
├── @pinecone-database/pinecone@3.0.0
├── @types/node@20.16.1
└── typescript@5.5.4
```
```


### Additional Context

_No response_

**Comment by aulorbe** [comment]
Hi @mpareja, thanks for reaching out! 

While the intention of our Typescript client is to run server-side, we purposefully do not _prevent_ users from running in the browser, as it's sometimes helpful during the development stages. 

We do, however, [issue a warning](https://github.com/pinecone-io/pinecone-ts-client/blob/d3231ea04dd8672fc14a1487e07ebbca64643555/src/pinecone.ts#L561-L568), which we hope users will heed when moving from development to production.

We do not plan on removing `dom` types from the client at this time, but we will consider this in the future!

**Comment by mpareja** [comment]
Hi @aulorbe,

Thanks for taking the time to respond! Just to be clear, I'm not suggesting precluding users from using the library in the browser.

The concern I'm raising is that the **Pinecone client is currently forcing all users to include DOM types** in their Typescript builds. Including DOM types in builds targeting Node.js only systems is not great since DOM-only functions aren't actually available for execution under node.

**Comment by aulorbe** [comment]
> Hi @aulorbe,
> 
> Thanks for taking the time to respond! Just to be clear, I'm not suggesting precluding users from using the library in the browser.
> 
> The concern I'm raising is that the **Pinecone client is currently forcing all users to include DOM types** in their Typescript builds. Including DOM types in builds targeting Node.js only systems is not great since DOM-only functions aren't actually available for execution under node.

Ah, I think I see where the confusion is. 

While our Typescript client can definitely run on Node (and is primarily aimed at users running in Node), it is not _only_ a Node module. You can see [here](https://github.com/pinecone-io/pinecone-ts-client/blob/main/.github/workflows/testing.yml#L36) in our workflow files that we also build to allow users to run in non-Node runtimes, such as [Edge](https://edge-runtime.vercel.app/). Edge is actually primarily where the `dom` types are required.
