### ISSUE TITLE
[Bug]? Excessive logging during build: 'Failed to find any user-provided fetch implementation' message in Pinecone SDK 3.0.1

### ISSUE THREAD

**Issue by ElectricCodeGuy** [pinecone-io/pinecone-ts-client#254]
**Is this a new bug?**
- [x] I believe this is a new bug
- [x] I have searched the existing Github issues and Community Forum, and I could not find an existing post for this bug

**Describe the bug**
After updating the Pinecone SDK from version v2.2.2 to 3.0.1, the build process is logging the message "Failed to find any user-provided fetch implementation. Using global fetch implementation." This message was not present in the previous version and is being logged during the Next.js build process. I do NOT use any edge runtime. The issue occurs both during local builds and in the Vercel logging when deployed to the website.

**Error information**
This is not an error per se, but a console log message that appears during the build process:
"Failed to find any user-provided fetch implementation. Using global fetch implementation."

The message is coming from the file:
`/node_modules/@pinecone-database/pinecone/dist/utils/fetch.js`

**Steps to reproduce the issue locally**
1. Update @pinecone-database/pinecone to version 3.0.1
2. Run `npm run build` or `next build` in a Next.js project that uses Pinecone
3. Observe the console output during the build process
4. Deploy the project to Vercel and observe the same message in the Vercel logs

**Environment**
- OS and version: Ubuntu 22.04.4 LTS
- Node version: v20.14.0
- Typescript SDK version: @pinecone-database/pinecone 3.0.1
- Next.js version: 14.2.6

**Additional context**
This message appears to be a new console.log statement added in the Pinecone SDK version 3.0.1. While it's not causing any apparent functionality issues, it's creating noise in the build output and could potentially be confusing for developers.

The message is logged when the SDK falls back to using the global fetch implementation. This behavior might be intentional, but the logging of this message during every build could be considered excessive.

The issue is not limited to local development environments but also occurs in production deployments on Vercel, potentially cluttering logs and making it harder to identify actual issues or errors.

**Comment by aulorbe** [comment]
Hi @ElectricCodeGuy! Thanks for bringing this to our attention. We will reduce the noise in the logs as soon as we have time.

**Comment by aqizzz** [comment]
Same issue

**Comment by trevoruptain** [comment]
Same issue, causes a lot of logging clutter

**Comment by samueldashadrach** [comment]
+1, same issue

**Comment by aulorbe** [comment]
Just merged [this PR](https://github.com/pinecone-io/pinecone-ts-client/pull/280) which closes this issue. Will issue patch release shortly!

**Comment by aulorbe** [comment]
Released! Pull down `v3.0.3` https://github.com/pinecone-io/pinecone-ts-client/releases/tag/v3.0.3 to get the latest code.

**Comment by christophemarois** [comment]
For people unable to upgrade to the fix above just yet, this will fix the noisy output:

```ts
const pc = new Pinecone({ fetchApi: fetch })
```
