### ISSUE TITLE
Could you export your types?

### ISSUE THREAD

**Issue by dalmaer** [pinecone-io/pinecone-ts-client#39]
I am duplicating the types in my clients.

"//Copied from pinecone library because their configOpts are unexported"

It would be fantastic if you exported them so clients wouldn't have to keep things up to date and have potential mismatches.

Thanks for your consideration!

**Comment by fozziethebeat** [comment]
It would be especially nice if the Index type was exposed.  That way we can create or fetch an index and pass it around with types.

**Comment by jhamon** [comment]
We recently released `v1.0.1`. The [v1 release](https://github.com/pinecone-io/pinecone-ts-client/releases) introduced a new client export with much better TypeScript support, including exported types and generics for metadata types. Check out the [Migration guide](https://github.com/pinecone-io/pinecone-ts-client/blob/main/v1-migration.md) and please open a new ticket if you come across a type export you need that is still missing.
