### ISSUE TITLE
.init() async thought

### ISSUE THREAD

**Issue by garviand** [pinecone-io/pinecone-ts-client#4]
I'm wondering whether the `.init()` function needs to be async. I see the benefit of fetching the project name, but it could be nice to initialize the client inside of a class constructor. Curious to hear people's thoughts.

Thank you for creating the TS client, it will be super helpful!

**Comment by drob** [comment]
+1, I'd rather it not be async. It's neat that it finds my index URL on its own from the API key, but I don't really need this.

If I have to store the API key in my env, I might as well store a pinecone base URL too. I'd rather do this than eat a remote call whenever I want to initialize a client in my code. (And if that means we could get rid of the init call entirely and do setup in the constructor, even better.)

**Comment by rschwabco** [comment]
For the moment, we're keeping this client aligned with out Python client. This means users shouldn't have to resolve their project id, which are essentially an internal implementation details users shouldn't care about.

**Comment by drob** [comment]
Could you at least make it cache this info? I'd like to be able to create clients without thinking about the latency that doing so will introduce.

**Comment by JoshuaPerk** [comment]
+1 the pattern is odd compared to how a majority of other clients are setup. If someone has a setup that doesn't support top-level await, this causes inconvenience

**Comment by bestfizzz** [comment]
+1 for Joshua, it is annoying
