### ISSUE TITLE
[Bug] createIndex() fails - "Index name must consist of lower case..."

### ISSUE THREAD

**Issue by Christopher-Hayes** [pinecone-io/pinecone-ts-client#41]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Unable to run `createIndex`. It throws an error every time that the name is incorrectly formatted.

### Expected Behavior

For `createIndex()` to run successfully.

### Steps To Reproduce

Run the following code with the latest package version, `v0.0.12`.

```js
const pinecone = new PineconeClient();
await pinecone.init({
  apiKey: PINECONE_API_KEY,
  environment: PINECONE_ENVIRONMENT,
});

const createIndexOptions = {
  name: 'test-table'
  dimension: 1536,
  metric: 'cosine',
  podType: 'p1',
};
console.log('Creating index with options: ', createIndexOptions);

await pinecone.createIndex(createIndexOptions);
```

### Relevant log output

```shell
[ErrorWithoutStackTrace: PineconeClient: Error calling createIndex: Index name must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character]
```
```


### Environment

```markdown
- **OS**: MacOS Monterey 12.6
- **Python version**: Python 3.9.6
- **Node version**: Node v18.9.0
- **Pinecone client version**: 0.0.12
```

### Additional Context

I checked "I believe this is a new bug" because it's required, but `createIndex()` also fails on `v0.0.11` with an unspecified error.

**Comment by huang47** [comment]
ran into exact the same problem when porting this to node as well

```
- **OS**: MacOS Monterey 13.2.1
- **Python version**: Python 3.11.2
- **Node version**: Node v16.15.1
- **Pinecone client version**: 0.0.12

**Comment by IdkwhatImD0ing** [comment]
Have you tried

pinecone.createIndex({createRequest: createIndexOptions});

**Comment by Philomath88** [comment]
I have the same error and this didn't do the trick for me: 

pinecone.createIndex({createRequest: createIndexOptions});

**Comment by drayilara** [comment]
Facing the same issue today. This is a blocker. Formating the index name as instructed by the error doesn't resolve the issue either.

**Comment by j796160836** [comment]
I'm experiencing this issues too.
Same value through web interface will ok but api fails.

**Comment by drayilara** [comment]
I believe it's a bug. I had to change to a single index architecture using namespaces to separate my users. I created that index on the GUI.

**Comment by j796160836** [comment]
I tested with similar method in Python worked.

```
import pinecone

PINECONE_API_KEY = "....."
PINECONE_ENVIRONMENT = "....."

pinecone.init(api_key=PINECONE_API_KEY,
              environment=PINECONE_ENVIRONMENT)

pinecone.create_index("myTestIndex", dimension=1536, metric='cosine', pods=1, replicas=1, pod_type="s1.x1")
```

Pretty sured it's a bug.

**Comment by robinmuhia** [comment]
Have any of you found a solution

**Comment by stevenmilstein** [comment]
I came across this [Langchain and Pinecone with Node.js: A Quick Start Tutorial - YouTube](https://www.youtube.com/watch?v=CF5buEVrYwo) . See line [16](https://github.com/developersdigest/Get-Started-With-Langchain-and-Pinecone-in-Node.js/blob/f2680921c1b6866668a72eb55fcd1893728b149a/1-createPineconeIndex.js#L15C1-L22C2)

I added `createRequest` and it works for me now.

```javascript
    const createClient = await client.createIndex({
      createRequest: {
        name: indexName,
        dimension: vectorDimension,
        metric: "cosine",
      },
    });
```

**Comment by jhamon** [comment]
The extra top-level `createRequest` key this method expected coupled with a lack of type safety meant a ton of people have been tripped up by this in the past. It was terrible UX.

We recently shipped a big update v1 update that simplifies these method parameters to what you were all expecting them to be in the first place: everything you need, nothing you don't. Check out the [release notes](https://github.com/pinecone-io/pinecone-ts-client/releases) and [v1 migration guide](https://github.com/pinecone-io/pinecone-ts-client/blob/main/v1-migration.md) to start using the new client.
