### ISSUE TITLE
Is this isomorphic?

### ISSUE THREAD

**Issue by gopidon** [pinecone-io/pinecone-ts-client#43]
I have successfully used this client on a nodejs server (server side). I am unable to use it directly in a client side React native app. Instantiating the client errors out at the following line of code

pinecone.init({
 ......
}
)

PineconeClient: Error getting project name: TypeError: undefined is not a function

**Comment by rschwabco** [comment]
No. At the moment, the `pinecone-ts-client` is not meant to be used outside of Node.js.
