### ISSUE TITLE
[Bug] createIndex switches to "Ready" state before it is actually is "Ready" for upserting

### ISSUE THREAD

**Issue by Kureev** [pinecone-io/pinecone-ts-client#46]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have a function that programmatically creates a pinecone index. It should be resolved only once the index is "ready" for upserting. 

```tsx
async createIndex(owner: string, repo: string) {
    const name = this.getIndexName(owner, repo)

    await this.client.createIndex({
        createRequest: {
            name,
            dimension: 1536,
        },
    })

    const checkStatus = async () => {
        const { status } = await this.client.describeIndex({
            indexName: name,
        })
        if (status?.state === IndexMetaStatusStateEnum.Ready) {
            return status
        } else {
            return new Promise((resolve) => {
                setTimeout(() => resolve(checkStatus()), 5000)
            })
        }
    }

    const status = await checkStatus()
    return this.getIndex(owner, repo)
}
```

However, I experience an issue with this approach: even though the status returns me `state: "Ready"`, the upserting command fails. If I create an index manually, the upserting works as intended. Hence, I think the issue is inside the logic that switches state to `Ready` way too early. 

### Expected Behavior

index's state switches to "Ready" only when index can be used for operations like upsert.

### Steps To Reproduce

1. Create a sample node application
2. Install pinecone
3. Create an instance of the pinecone using `new PineconeClient()`
4. Call `.createIndex` with arbitrary parameters. For example,
```tsx
const index = await client.createIndex({
    createRequest: {
        name,
        dimension: 1536,
    },
})
```
5. Implement a similar function to the one in the example to await for index status to switch to `Ready`
6. Try to upsert some data. For example, you can write a function similar to this:
```tsx
async store(docs: Document[], pineconeIndex: VectorOperationsApi) {
    for (const chunk of this.splitDocuments(docs)) {
        await PineconeStore.fromDocuments(
            chunk,
            new OpenAIEmbeddings({
                verbose: true,
            }),
            {
                pineconeIndex,
            }
        )
    }
}
```
7. You will have an error without a stack trace. However, if you pre-create an index and remove index creation part from the code, everything works fine.

### Environment

```markdown
- **OS**:
- **Language version**:
- **Pinecone client version**:
```

**Comment by aulorbe** [comment]
Hello! Are you still experiencing this issue? From everything we've seen on our end, the status of an index should only return `Ready` when it is indeed ready for upserting.

Please let us know!
