### ISSUE TITLE
[Bug] delete1 method does not allow for filter object

### ISSUE THREAD

**Issue by freakyfriday** [pinecone-io/pinecone-ts-client#48]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Current delete1 method does not include filter object to request:

see - https://github.com/pinecone-io/pinecone-ts-client/blob/77ec3aea0a6da2cfccf129f68f1b986e4aad1bc5/src/pinecone-generated-ts-fetch/apis/VectorOperationsApi.ts#L131

```
 async delete1Raw(requestParameters: Delete1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters.ids) {
            queryParameters['ids'] = requestParameters.ids;
        }

        if (requestParameters.deleteAll !== undefined) {
            queryParameters['deleteAll'] = requestParameters.deleteAll;
        }

        if (requestParameters.namespace !== undefined) {
            queryParameters['namespace'] = requestParameters.namespace;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Api-Key"] = this.configuration.apiKey("Api-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/vectors/delete`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * The `Delete` operation deletes vectors, by id, from a single namespace. You can delete items by their id, from a single namespace.
     * Delete
     */
    async delete1(requestParameters: Delete1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.delete1Raw(requestParameters, initOverrides);
        return await response.value();
    }
```

### Expected Behavior

As per docs, filter object should be included - https://docs.pinecone.io/reference/delete_post

### Steps To Reproduce

1. use filter property in delete1 request 

### Environment

```markdown
"@pinecone-database/pinecone": "^0.0.14",
```

**Comment by mulhoon** [comment]
Adding the filter to `queryParameters.filter` didn't work for me. 
For now, I just manually call the API... 🤷‍♂️

```js
await fetch(
  `https://${INDEX}.svc.${REGION}.pinecone.io/vectors/delete?namespace=${NAMESPACE}`,
  {
    method: 'POST',
    headers: {
      'Api-Key': API_KEY,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      filter: {
        source: { $in: [filename] }
      }
    })
  }
)
```

**Comment by jhamon** [comment]
Sorry you ran into this issue. We've recently been putting in a lot of work to improve the pinecone typescript client so you might be interested in checking out the v1 release (specifically `1.0.1`). Here are the [release notes](https://github.com/pinecone-io/pinecone-ts-client/releases) and the [v1 migration guide](https://github.com/pinecone-io/pinecone-ts-client/blob/main/v1-migration.md) to get started using the new client.
