### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by transitive-bullshit** [pinecone-io/pinecone-ts-client#5]
I've been using https://github.com/rileytomasek/pinecone-client so far, but would prefer to use the official version if it's comparable quality.

Here's some feedback on expectations for this type of NPM package:

<img width="724" alt="CleanShot 2023-02-16 at 17 17 11@2x" src="https://user-images.githubusercontent.com/552829/219509677-4975ac18-01ce-4f98-936d-9cca48066ff3.png">

1. `@types/node`, `dotenv`, `ts-node`, and `typescript` should not be dependencies; they should be dev dependencies. Currently, every time you `npm install` and `import` this package, you're importing some massive and completely unrelated dependencies like all of typescript.
2. `axios` should ideally be replaced by `fetch`. Serverless and edge usage is growing exponentially, and `fetch` is the default HTTP provider in these environments.
3. Consider using `typedoc` to generate docs since right now it's difficult to tell what's auto-generated by OpenAI and what's actually used.

Hope this feedback is helpful && thanks,

**Comment by rschwabco** [comment]
Here's a PR to replace Axios with Fetch: https://github.com/pinecone-io/pinecone-ts-client/pull/10

**Comment by rschwabco** [comment]
Merged #10.

**Comment by transitive-bullshit** [comment]
Thanks @rschwabco 🙏 

Looks like `axios` is still listed as a dependency after the merge btw; is that an oversight, or is it still required for some use cases?
