### ISSUE TITLE
[Feature] Client init shouldn't need to be async / project name should be internal

### ISSUE THREAD

**Issue by jake-sager** [pinecone-io/pinecone-ts-client#50]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

The client init is async because it needs to resolve the project name. This is a pretty weird pattern -- why can't we just pass in `project name` like api keys / index names / etc? Seems like a case of an internal implementation detail making the client rather clunky. 

Perhaps separately, confusing that the client needs to consider an internal implementation detail like project name (but it's a _different_ project name from the user created one, which is also weird?) is so exposed to client. This adds clunkiness / extra work to the client. Also adds a step to the HTTP call.

**Comment by anawishnoff** [comment]
This has been fixed in the January v2 release, so closing this issue
