### ISSUE TITLE
[Bug] Error when trying to delete by filter

### ISSUE THREAD

**Issue by CobaltBlueDW** [pinecone-io/pinecone-ts-client#54]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I've tried using the example docs on https://docs.pinecone.io/docs/metadata-filtering#deleting-vectors-by-metadata-filter to delete vectors by filter:
`await index._delete({
      filter: {
          category: "favorites",
      },
});`
, and I receive error message:
`PineconeError: PineconeClient: Error calling _delete: PineconeError: PineconeClient: Error calling _deleteRaw: RequiredError: Required parameter requestParameters.deleteRequest was null or undefined when calling _delete.`

### Expected Behavior

Expect the query to execute.

### Steps To Reproduce

1. Add vectors to index with some meta data.
2. Ensure library is up to date: 0.0.14
3. Attempt to delete vectors using that meta data.

`import { PineconeClient } from '@pinecone-database/pinecone';`
`const pinecone = new PineconeClient();`
`const index = pinecone.Index("example");`
`await index._delete({`
`  filter: {`
`      category: "favorites",`
`  },`
` });`

### Relevant log output

```shell
error [PineconeError: PineconeClient: Error calling _delete: PineconeError: PineconeClient: Error calling _deleteRaw: RequiredError: Required parameter requestParameters.deleteRequest was null or undefined when calling _delete.]
```

### Environment

```markdown
- **OS**: Windows
- **Language version**: Node.js 18.14.0
- **Pinecone client version**: 0.0.14
```

**Comment by vamonke** [comment]
@CobaltBlueDW you'll need to put the object in a `deleteRequest` property. I looked inside the `DeleteOperationRequest` type, changed my argument and now it works for me.

```
await index._delete({
    deleteRequest: {
        filter: {
            category: "favorites",
        },
    }
});
```

**Comment by jgard1** [comment]
Having a similar bug. Currently trying the above solution and getting a response of "{}". Hopefully someone from Pinecone will either fix the bug or the documentation, whichever is incorrect. 
![image](https://github.com/pinecone-io/pinecone-ts-client/assets/44043414/c31d9079-8dc8-41e3-9fd6-38f553f07725)

**Comment by jhamon** [comment]
@jgard1 You've probably figured this out or moved on by now, but there's a missing top-level `deleteRequest` key needed as in the example above. Also (I'm not sure but) you may need to use the `$eq` and wrap your two conditions in an `$and` along the lines of

```typescript
const deleteRequest = {
  filter: {
    $and: [
      genre: { $eq: "documentary" },
      year: { $eq: 2019 }
    ]
  }
}
await index._delete({ deleteRequest })
```

We shipped a big update in v1. Check out the [release notes](https://github.com/pinecone-io/pinecone-ts-client/releases) and [v1 migration guide](https://github.com/pinecone-io/pinecone-ts-client/blob/v1.0.0/v1-migration.md) to see what's new.
