### ISSUE TITLE
Error initializing client

### ISSUE THREAD

**Issue by nicot** [pinecone-io/pinecone-ts-client#7]
I'm getting an error initializing the client:

```
PineconeClient: Error getting project name: Error: read ECONNRESET
```

I don't think this line should have `controller` in it:

https://github.com/pinecone-io/pinecone-ts-client/blob/dd1a14323c5736f7a25bd85ae26dad652942410d/src/index.ts#L83

Some docs reference controller, but it only works when the controller subdomain is not included.

Additionally, this method should not log an error, it should throw, because the client is unusable without the project name.

**Comment by rschwabco** [comment]
Could you please share how you're initializing the client? 

The  `controller` endpoint exposes the available methods for the  Pinecone control plane.  The project name resolves the project name automatically.

**Comment by nicot** [comment]
I think I was doing this incorrectly and passing in `734a21.svc.us-east1-gcp`, but it's just `us-east1-gcp`, right? Sorry for the bad bug report!
