### ISSUE TITLE
[Bug] createIndex fails

### ISSUE THREAD

**Issue by roastedcpu** [pinecone-io/pinecone-ts-client#81]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Api fails to create an index.

Noticed I wasn't able to use JS client to create an index -> Tried with curl -> same response

### Expected Behavior

Should return 200 OK and create the index

### Steps To Reproduce

curl -i -X POST https://controller.gcp-starter.pinecone.io/databases \
  -H 'Api-Key: REDACTED' \
  -H 'Content-Type: application/json' \
  -d '{
        "name": "docs1",
        "dimension": 1536,
        "metadataConfig": {
          "indexed": ["path"]
        }
  }'

### Relevant log output

```shell
Failed to deserialize the JSON body into the target type: missing field `metric` at line 7 column 3
```

**Comment by jhamon** [comment]
The error message is telling you that you're missing a value in the `metric` field of the request body. You can use 'euclidean', 'cosine', or 'dotproduct'. For descriptions of these, read [check these docs on distance metrics](https://docs.pinecone.io/docs/indexes#distance-metrics)

I'm going to close this ticket because it is not related to the typescript client.

**Comment by cchoi94** [comment]
@jhamon Thanks for the support! I've cloned the semantic search beginners' typescript guide and added the missing `metric` field to the `createIndex` method, however, after rerunning the `npm start -- load --csvPath=test.csv --column=question1` I am still running into the same issue. Am I missing something perhaps?

**Comment by cchoi94** [comment]
Just an update, I got a work around here https://github.com/pinecone-io/semantic-search-example/issues/6. Tho I feel the issue perhaps still remains. Where `cosine` is not set as the default somewhere?

**Comment by jhamon** [comment]
Thanks for the feedback. I'm not sure what's going on here, but I'll dig in to try to get to the bottom of it. It definitely seems like there is some unnecessary friction here.

**Comment by cchoi94** [comment]
@jhamon thanks for looking into it. Lmk if there is anything I can do to help
