### ISSUE TITLE
Select vectors based on namespace

### ISSUE THREAD

**Issue by davide221** [pinecone-io/pinecone-ts-client#9]
Hi! I have different clusters of vectors with different namespaces, but i can not find the right request to select them based on namespace if exists something like this.

**Comment by rschwabco** [comment]
It's part of `QueryRequest`: 

```
const queryRequest: QueryRequest = {
      topK: 1,
      vector: getRandomVector(vectors).values,
      namespace
    }
const queryResponse = await index.query({ queryRequest })
```
